memo\
・Python3.7、TensorFlow-gpu=1.4.0で動作

In [1]:
!nvidia-smi

Thu May  5 15:03:15 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   42C    P0    27W / 250W | Function Not Found   |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [3]:
ls

 _cache/                       precision_recall.py   test.ipynb
 dnnlib/                       __pycache__/          tfrecords_test/
 evaluate_results/             README.md             tfrecords_test_2/
 experiments.py                run_metric.py         tfrecords_test_3/
 ffhq_datareader.py            stylegan2encoder/     utils.py
'Precision and Recall.ipynb'   teaser-image.png


In [2]:
# driveマウント
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

KeyError: 'TBE_EPHEM_CREDS_ADDR'

In [3]:
cd /content/drive/MyDrive/research/katoyu-improved-precision-and-recall-metric/

/content/drive/MyDrive/research/katoyu-improved-precision-and-recall-metric


In [4]:
# !git clone https://github.com/kynkaat/improved-precision-and-recall-metric.git

In [5]:
!pip uninstall -y tensorflow tensorflow-gpu tensorboard tensorflow-estimator
!pip install tensorflow-gpu==1.14.0

Found existing installation: tensorflow-gpu 1.14.0
Uninstalling tensorflow-gpu-1.14.0:
  Successfully uninstalled tensorflow-gpu-1.14.0
Found existing installation: tensorboard 1.14.0
Uninstalling tensorboard-1.14.0:
  Successfully uninstalled tensorboard-1.14.0
Found existing installation: tensorflow-estimator 1.14.0
Uninstalling tensorflow-estimator-1.14.0:
  Successfully uninstalled tensorflow-estimator-1.14.0
  Using cached tensorflow_gpu-1.14.0-cp37-cp37m-manylinux1_x86_64.whl (377.1 MB)
  Using cached tensorboard-1.14.0-py3-none-any.whl (3.1 MB)
  Using cached tensorflow_estimator-1.14.0-py2.py3-none-any.whl (488 kB)


In [ ]:
ls /content/drive/MyDrive/research/improved-precision-and-recall-metric/tfrecords/ffhq

In [4]:
ls /content/drive/MyDrive/research/katoyu-improved-precision-and-recall-metric/tfrecords_test_3

ffhq-r02.tfrecords  ffhq-r03.tfrecords  ffhq-r04.tfrecords  ffhq-r05.tfrecords


# Python バージョン入れ直し

In [ ]:
# !python -V 

In [ ]:
# %%bash

# MINICONDA_INSTALLER_SCRIPT=Miniconda3-4.5.4-Linux-x86_64.sh
# MINICONDA_PREFIX=/usr/local
# wget https://repo.continuum.io/miniconda/$MINICONDA_INSTALLER_SCRIPT
# chmod +x $MINICONDA_INSTALLER_SCRIPT
# ./$MINICONDA_INSTALLER_SCRIPT -b -f -p $MINICONDA_PREFIX

In [ ]:
# import sys
# _ = (sys.path.append("/usr/local/lib/python3.6/site-packages"))

# 実行

In [5]:
!python run_metric.py \
--data_dir /content/drive/MyDrive/research/katoyu-improved-precision-and-recall-metric/tfrecords_test_3/ \
--truncation_sweep

/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or 

In [9]:
!python run_metric.py \
--data_dir /content/drive/MyDrive/research/katoyu-improved-precision-and-recall-metric/tfrecords_test_3/ \
--ccr_sweep

shell-init: error retrieving current directory: getcwd: cannot access parent directories: Transport endpoint is not connected
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Transport endpoint is not connected
python3: can't open file 'run_metric.py': [Errno 107] Transport endpoint is not connected


# MEMO

Error
```
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/usr/local/lib/python3.7/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.7/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.7/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.7/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.7/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.7/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
WARNING:tensorflow:From /content/drive/MyDrive/research/improved-precision-and-recall-metric/dnnlib/tflib/tfutil.py:34: The name tf.Dimension is deprecated. Please use tf.compat.v1.Dimension instead.

WARNING:tensorflow:From /content/drive/MyDrive/research/improved-precision-and-recall-metric/dnnlib/tflib/tfutil.py:74: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

WARNING:tensorflow:From /content/drive/MyDrive/research/improved-precision-and-recall-metric/dnnlib/tflib/tfutil.py:128: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

Initializing TensorFlow...

WARNING:tensorflow:From /content/drive/MyDrive/research/improved-precision-and-recall-metric/dnnlib/tflib/tfutil.py:97: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.

WARNING:tensorflow:From /content/drive/MyDrive/research/improved-precision-and-recall-metric/dnnlib/tflib/tfutil.py:109: The name tf.set_random_seed is deprecated. Please use tf.compat.v1.set_random_seed instead.

Streaming data using ffhq_datareader.TFRecordDataset...

WARNING:tensorflow:From /content/drive/MyDrive/research/improved-precision-and-recall-metric/ffhq_datareader.py:75: The name tf.python_io.TFRecordOptions is deprecated. Please use tf.io.TFRecordOptions instead.

WARNING:tensorflow:From /content/drive/MyDrive/research/improved-precision-and-recall-metric/ffhq_datareader.py:75: The name tf.python_io.TFRecordCompressionType is deprecated. Please use tf.compat.v1.python_io.TFRecordCompressionType instead.

WARNING:tensorflow:From /content/drive/MyDrive/research/improved-precision-and-recall-metric/ffhq_datareader.py:76: tf_record_iterator (from tensorflow.python.lib.io.tf_record) is deprecated and will be removed in a future version.
Instructions for updating:
Use eager execution and: 
`tf.data.TFRecordDataset(path)`
WARNING:tensorflow:From /content/drive/MyDrive/research/improved-precision-and-recall-metric/ffhq_datareader.py:132: The name tf.data.Iterator is deprecated. Please use tf.compat.v1.data.Iterator instead.

WARNING:tensorflow:From /content/drive/MyDrive/research/improved-precision-and-recall-metric/ffhq_datareader.py:132: DatasetV1.output_types (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.data.get_output_types(dataset)`.
WARNING:tensorflow:From /content/drive/MyDrive/research/improved-precision-and-recall-metric/ffhq_datareader.py:132: DatasetV1.output_shapes (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.data.get_output_shapes(dataset)`.
WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tensorflow/python/data/ops/iterator_ops.py:348: Iterator.output_types (from tensorflow.python.data.ops.iterator_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.data.get_output_types(iterator)`.
WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tensorflow/python/data/ops/iterator_ops.py:349: Iterator.output_shapes (from tensorflow.python.data.ops.iterator_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.data.get_output_shapes(iterator)`.
WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tensorflow/python/data/ops/iterator_ops.py:351: Iterator.output_classes (from tensorflow.python.data.ops.iterator_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.data.get_output_classes(iterator)`.
Dataset info.
Dataset shape = [3, 1024, 1024]
Dynamic range = [0, 255]
Label size    = 0 

Running StyleGAN truncation sweep...
Initializing VGG-16 model...
Downloading https://drive.google.com/uc?id=1fk6r8vetqpRShtEODXm9maDytbMkHLfa&confirm=t ... done
Initializing StyleGAN...

Downloading https://drive.google.com/uc?id=1zwhFLIvQYyNVOwQCLAhIJHmN7sjvAM84&confirm=t ... done
WARNING:tensorflow:From <string>:364: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Truncation 1
Reading real images...
2022-04-26 12:57:50.620767: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: /content/drive/MyDrive/research/improved-precision-and-recall-metric/tfrecords_test/ffhq-r10.tfrecords; No space left on device
	 [[{{node IteratorGetNext}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_metric.py", line 93, in <module>
    main()
  File "run_metric.py", line 84, in main
    compute_stylegan_truncation(**truncation_config)
  File "/content/drive/MyDrive/research/improved-precision-and-recall-metric/experiments.py", line 71, in compute_stylegan_truncation
    real_batch, _ = datareader.get_minibatch_np(end - begin)
  File "/content/drive/MyDrive/research/improved-precision-and-recall-metric/ffhq_datareader.py", line 153, in get_minibatch_np
    return tflib.run(self._tf_minibatch_np)
  File "/content/drive/MyDrive/research/improved-precision-and-recall-metric/dnnlib/tflib/tfutil.py", line 26, in run
    return tf.get_default_session().run(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: /content/drive/MyDrive/research/improved-precision-and-recall-metric/tfrecords_test/ffhq-r10.tfrecords; No space left on device
	 [[node IteratorGetNext (defined at /content/drive/MyDrive/research/improved-precision-and-recall-metric/ffhq_datareader.py:146) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.


Errors may have originated from an input operation.
Input Source operations connected to node IteratorGetNext:
 Dataset/IteratorV2 (defined at /content/drive/MyDrive/research/improved-precision-and-recall-metric/ffhq_datareader.py:132)

Original stack trace for 'IteratorGetNext':
  File "run_metric.py", line 93, in <module>
    main()
  File "run_metric.py", line 84, in main
    compute_stylegan_truncation(**truncation_config)
  File "/content/drive/MyDrive/research/improved-precision-and-recall-metric/experiments.py", line 71, in compute_stylegan_truncation
    real_batch, _ = datareader.get_minibatch_np(end - begin)
  File "/content/drive/MyDrive/research/improved-precision-and-recall-metric/ffhq_datareader.py", line 152, in get_minibatch_np
    self._tf_minibatch_np = self.get_minibatch_tf()
  File "/content/drive/MyDrive/research/improved-precision-and-recall-metric/ffhq_datareader.py", line 146, in get_minibatch_tf
    return self._tf_iterator.get_next()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 426, in get_next
    output_shapes=self._structure._flat_shapes, name=name)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/gen_dataset_ops.py", line 1947, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()
```